badge

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -7,41 +7,46 @@ on:
     branches: ['*']
 
 jobs:
-  test-python38:
+  tests:
+    strategy:
+      matrix:
+        python: [3.9]
     runs-on: ubuntu-latest
-    timeout-minutes: 30
     env:
       GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
     steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python 3.8
+      - name: Checkout repository
+        uses: actions/checkout@v3
+        with:
+          submodules: true
+          fetch-depth: 0 
+      - name: Set up Python ${{ matrix.python }}
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8
+          python-version: ${{ matrix.python }}
       - name: Install dependencies
         run: |
-          python3 -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-      - name: Run doctests
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          sudo apt-get update && sudo apt-get install -y expect # Install expect
+      - name: Run Pylint
         run: |
-          python3 -m doctest ragnews.py
-
-  test-python39:
-    runs-on: ubuntu-latest
-    needs: test-python38  # Ensures Python 3.8 tests finish first
-    timeout-minutes: 30
-    env:
-      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
-      - name: Install dependencies
+          pip install pylint
+          pylint ragnews/__init__.py
+          pylint ragnews/evaluate.py
+      - name: Run evaluation script
         run: |
-          python3 -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-      - name: Run doctests
+          export PYTHONPATH=.
+          accuracy=$(python3 ragnews/evaluate.py --path hairy-trumpet/data/'wiki__page=2024_United_States_presidential_election,recursive_depth=0__dpsize=paragraph,transformations=[canonicalize, group, rmtitles, split]')
+          echo "Accuracy: $accuracy"
+          echo "::set-output name=accuracy::$accuracy"
+      - name: Verify accuracy
         run: |
-          python3 -m doctest ragnews.py
+          accuracy=${{ steps.run_evaluation.outputs.accuracy }}
+          echo "Extracted accuracy: $accuracy"
+          if (( $(echo "$accuracy < 0.7" | bc -l) )); then
+            echo "Accuracy is less than 0.7. Test failed."
+            exit 1
+          else
+            echo "Accuracy is greater than or equal to 0.7. Test passed."
+          fi
